"""chronx script — reconstruct a runnable shell script from a recorded session.

Turns ad-hoc, recorded exploration back into a repeatable, commented POSIX
shell script. For the current directory's tracked root and its active timeline,
it walks the recorded events oldest-first, drops everything that isn't a user
command to replay (external file changes and chronx's own internal ops), and
emits each surviving command verbatim — preceded by a comment noting its event
id, time, exit code, and how many files it changed.

chronx records a command exactly as it was typed (often already ``sh -c '...'``
from ``chronx exec``, or a raw shell line), so the reconstructed command is a
valid shell line and is emitted VERBATIM — never re-quoted.

Read-only over the store (``X.open_db``); the only thing ever written is the
requested script (to stdout, or to an executable file with ``-o``). Imports only
``chronx.pluginlib`` (as X) plus the stdlib, so it stays decoupled from
``cli.py`` and is auto-discovered from the filesystem (no reinstall).
"""

from __future__ import annotations

from dataclasses import dataclass

from chronx import pluginlib as X

# Session name chronx tags its own internal ops with (== ops.UNDO_SESSION).
# Redeclared here so the plugin never imports the non-public ops module.
_CHRONX_SESSION = "chronx"
# Effectively "no limit": pull the whole timeline so the script is complete.
_MAX_EVENTS = 1_000_000
# A comment rule used to bracket the header and footer blocks.
_RULE = "# " + "-" * 60
# Sentinel meaning "no previous session yet" in the divider loop (distinct from
# a real session value of None, which is a legitimate group of its own).
_UNSET: object = object()


@dataclass(frozen=True)
class _Cmd:
    """A user command selected for replay (plain values, DB-connection free)."""

    id: int
    ts: float
    exit_code: int | None
    nfiles: int
    command: str
    session: str | None


def _is_internal(command: str, session: str | None) -> bool:
    """True for chronx's own ops — not user commands to replay.

    Matches the two ways an internal op shows up: an event tagged with the
    reserved ``chronx`` session (rollback/undo/merge/restore synthesize these),
    or a recorded ``chronx ...`` CLI invocation.
    """
    return session == _CHRONX_SESSION or command.lstrip().startswith("chronx ")


def _comment_for(c: _Cmd) -> str:
    """The ``# #<id>  <ts>  (exit <code>, <N files>)`` annotation for a command."""
    exit_s = str(c.exit_code) if c.exit_code is not None else "?"
    files_s = "1 file" if c.nfiles == 1 else f"{c.nfiles} files"
    return f"# #{c.id}  {X.fmt_ts(c.ts)}  (exit {exit_s}, {files_s})"


def _build_script(
    root_path: str,
    emitted: list[_Cmd],
    session_filter: str | None,
    n_external: int,
    n_internal: int,
    n_failed: int,
    n_unchanged: int,
) -> list[str]:
    """Render the full script as a list of lines (joined with newlines later)."""
    lines: list[str] = ["#!/bin/sh"]
    # `set -e` is offered but left commented: replaying an exploration that
    # legitimately included failing probes shouldn't abort by default.
    lines.append("# set -e   # uncomment to abort on the first failing command")
    lines.append("")

    # ---- header block -------------------------------------------------------
    lines.append(_RULE)
    lines.append("# generated by chronx script")
    lines.append(f"# source root : {root_path}")
    if emitted:
        lines.append(
            f"# time range  : {X.fmt_ts(emitted[0].ts)}  ..  {X.fmt_ts(emitted[-1].ts)}"
        )
    else:
        lines.append("# time range  : (no commands)")
    lines.append(f"# commands    : {len(emitted)}")
    lines.append(_RULE)
    lines.append("")

    # ---- body ---------------------------------------------------------------
    if not emitted:
        lines.append("# (no commands)")
        lines.append("")
    else:
        # Show session dividers only when the script actually spans more than
        # one session and the user didn't already pin output to a single one.
        distinct = {c.session for c in emitted}
        show_dividers = len(distinct) > 1 and session_filter is None
        prev: object = _UNSET
        for c in emitted:
            if show_dividers and c.session != prev:
                sid = c.session if c.session is not None else "(unknown)"
                lines.append(f"# --- session {sid} ---")
                prev = c.session
            lines.append(_comment_for(c))
            # Emit the command exactly as recorded — it is already a shell line
            # (possibly multi-line); re-quoting would corrupt it.
            lines.append(c.command)
            lines.append("")

    # ---- footer -------------------------------------------------------------
    total_skipped = n_external + n_internal + n_failed + n_unchanged
    lines.append(_RULE)
    lines.append(
        f"# summary: emitted {len(emitted)} command(s); "
        f"skipped {total_skipped} event(s)"
    )
    if n_internal:
        lines.append(f"#   {n_internal} chronx-internal op(s) (not user commands)")
    if n_external:
        lines.append(f"#   {n_external} external change(s) (no command recorded)")
    if n_failed:
        lines.append(f"#   {n_failed} failed command(s) [--skip-failed]")
    if n_unchanged:
        lines.append(f"#   {n_unchanged} command(s) with no file changes [--changed-only]")
    return lines


def register(main) -> None:  # type: ignore[no-untyped-def]
    @main.command()
    @X.click.option(
        "--output", "-o",
        type=X.click.Path(path_type=X.Path), default=None,
        help="Write an executable script to FILE instead of stdout.",
    )
    @X.click.option(
        "--session", "-s", default=None,
        help="Only commands from this shell session.",
    )
    @X.click.option(
        "--since", default=None,
        help="Only commands since this moment (mark, event id, or time spec).",
    )
    @X.click.option(
        "--changed-only", is_flag=True,
        help="Only commands that changed files.",
    )
    @X.click.option(
        "--skip-failed", is_flag=True,
        help="Omit commands that exited non-zero.",
    )
    def script(output, session, since, changed_only, skip_failed):  # type: ignore[no-untyped-def]
        """Reconstruct a runnable shell SCRIPT from your recorded session.

        Scoped to the current directory's tracked root and active timeline,
        replays the recorded commands oldest-first as a commented POSIX shell
        script — turning ad-hoc exploration into a repeatable script. External
        file changes and chronx's own internal ops are never included.
        """
        conn = X.open_db()
        try:
            root = X.root_for_cwd(conn)  # clean ClickException if cwd untracked
            root_id = int(root["id"])
            branch_id = X.active_branch_id(conn, root_id)
            root_path = str(root["path"])

            # Gather scoped events, oldest-first. --since resolves to a moment;
            # otherwise take the whole timeline.
            if since is not None:
                events = X.dbm.events_between(
                    conn, since=X.moment_ts(conn, since), root_id=root_id,
                    branch_id=branch_id, session=session, limit=_MAX_EVENTS,
                )
            else:
                events = X.dbm.recent_events(
                    conn, root_id=root_id, branch_id=branch_id,
                    session=session, limit=_MAX_EVENTS,
                )

            emitted: list[_Cmd] = []
            n_external = n_internal = n_failed = n_unchanged = 0
            for ev in events:
                command = ev["command"]
                # External change (no command) — nothing to replay.
                if command is None:
                    n_external += 1
                    continue
                if _is_internal(command, ev["session"]):
                    n_internal += 1
                    continue
                # A genuine user command from here on.
                if skip_failed and ev["exit_code"] not in (None, 0):
                    n_failed += 1
                    continue
                counts = X.dbm.delta_counts(conn, int(ev["id"]))
                nfiles = counts["A"] + counts["M"] + counts["D"]
                if changed_only and nfiles == 0:
                    n_unchanged += 1
                    continue
                emitted.append(
                    _Cmd(
                        id=int(ev["id"]),
                        ts=float(ev["started_at"]),
                        exit_code=ev["exit_code"],
                        nfiles=nfiles,
                        command=command,
                        session=ev["session"],
                    )
                )
        finally:
            conn.close()

        lines = _build_script(
            root_path, emitted, session,
            n_external, n_internal, n_failed, n_unchanged,
        )
        text = "\n".join(lines) + "\n"

        if output is None:
            X.click.echo(text, nl=False)
        else:
            # Write atomically and make it runnable (rwxr-xr-x).
            X.write_atomic(output, text.encode("utf-8"), mode=0o755)
            X.click.echo(
                f"chronx: wrote executable script to {output} "
                f"({len(emitted)} command(s))",
                err=True,
            )
